name: Deploy to Self Hosted Server

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

env:
  IMAGE_NAME: yourdockerhubusername/yourapp
  CONTAINER_NAME: myapp

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Latest Image
        run: docker pull $IMAGE_NAME:latest

      - name: Stop Old Container
        run: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

      - name: Run New Container
        run: |
          docker run -d \
            --name $CONTAINER_NAME \
            --restart always \
            -p 80:3000 \
            $IMAGE_NAME:latest
